import { AspectRatio, AIProviderOption } from "./types";

export const ASPECT_RATIOS: Record<string, AspectRatio> = {
  "1:1": { id: "1:1", label: "Square 1:1", ratio: "1:1", width: 1080, height: 1080 },
  "4:5": { id: "4:5", label: "Portrait 4:5", ratio: "4:5", width: 1080, height: 1350 },
  "9:16": { id: "9:16", label: "Story 9:16", ratio: "9:16", width: 1080, height: 1920 },
  "16:9": { id: "16:9", label: "Landscape 16:9", ratio: "16:9", width: 1920, height: 1080 },
  "A4-P": { id: "A4-P", label: "A4 Portrait", ratio: "A4 Portrait", width: 794, height: 1123 },
  "A4-L": { id: "A4-L", label: "A4 Landscape", ratio: "A4 Landscape", width: 1123, height: 794 },
  letter: { id: "letter", label: "Letter", ratio: "Letter", width: 816, height: 1056 },
  custom: { id: "custom", label: "Custom", ratio: "Custom", width: 800, height: 800 },
};

export const AI_PROVIDERS: AIProviderOption[] = [
  {
    id: "openai",
    name: "OpenAI",
    requiresApiKey: true,
    docsUrl: "https://platform.openai.com/api-keys",
    models: [
      { id: "gpt-4o", name: "GPT-4o", contextWindow: 128000, maxOutput: 16384 },
      {
        id: "gpt-4o-mini",
        name: "GPT-4o Mini",
        contextWindow: 128000,
        maxOutput: 16384,
      },
      {
        id: "gpt-4-turbo",
        name: "GPT-4 Turbo",
        contextWindow: 128000,
        maxOutput: 4096,
      },
    ],
  },
  {
    id: "gemini",
    name: "Google Gemini",
    requiresApiKey: true,
    docsUrl: "https://ai.google.dev/gemini-api/docs/api-keys",
    models: [
      {
        id: "gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        contextWindow: 1048576,
        maxOutput: 8192,
      },
      {
        id: "gemini-1.5-flash",
        name: "Gemini 1.5 Flash",
        contextWindow: 1048576,
        maxOutput: 8192,
      },
      {
        id: "gemini-2.0-flash-exp",
        name: "Gemini 2.0 Flash",
        contextWindow: 1048576,
        maxOutput: 8192,
      },
    ],
  },
  {
    id: "claude",
    name: "Anthropic Claude",
    requiresApiKey: true,
    docsUrl: "https://console.anthropic.com/",
    models: [
      {
        id: "claude-3-5-sonnet-20241022",
        name: "Claude 3.5 Sonnet",
        contextWindow: 200000,
        maxOutput: 8192,
      },
      {
        id: "claude-3-haiku-20240307",
        name: "Claude 3 Haiku",
        contextWindow: 200000,
        maxOutput: 4096,
      },
    ],
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    requiresApiKey: true,
    docsUrl: "https://openrouter.ai/keys",
    models: [
      {
        id: "openrouter/free",
        name: "OpenRouter Free (Auto-Select)",
        contextWindow: 8192,
        maxOutput: 4096,
      },
      {
        id: "google/gemma-4-31b-it:free",
        name: "Google Gemma 4 31B (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "google/gemma-4-26b-a4b-it:free",
        name: "Google Gemma 4 26B A4B (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-120b:free",
        name: "OpenAI GPT-OSS 120B (Free)",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-20b:free",
        name: "OpenAI GPT-OSS 20B (Free)",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-super-120b-a12b:free",
        name: "NVIDIA Nemotron 3 Super 120B (Free)",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-nano-30b-a3b:free",
        name: "NVIDIA Nemotron 3 Nano 30B (Free)",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free",
        name: "NVIDIA Nemotron 3 Nano Omni (Free)",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-nano-12b-v2-vl:free",
        name: "NVIDIA Nemotron Nano 12B v2 VL (Free)",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nemotron-nano-9b-v2:free",
        name: "NVIDIA Nemotron Nano 9B v2 (Free)",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "poolside/laguna-xs-2.1:free",
        name: "Poolside Laguna XS 2.1 (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "poolside/laguna-m.1:free",
        name: "Poolside Laguna M.1 (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "qwen/qwen3-next-80b-a3b-instruct:free",
        name: "Qwen3 Next 80B A3B (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "tencent/hy3:free",
        name: "Tencent HY3 (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-4o",
        name: "OpenAI GPT-4o",
        contextWindow: 128000,
        maxOutput: 16384,
      },
      {
        id: "anthropic/claude-3.5-sonnet",
        name: "Claude 3.5 Sonnet",
        contextWindow: 200000,
        maxOutput: 8192,
      },
      {
        id: "google/gemini-1.5-pro",
        name: "Gemini 1.5 Pro",
        contextWindow: 1048576,
        maxOutput: 8192,
      },
      {
        id: "meta-llama/llama-3.1-70b",
        name: "Llama 3.1 70B",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "NVIDIA Nemotron 3 Super",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "qwen/qwen3-coder",
        name: "Qwen3 Coder",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "google/gemma-4-31b-it",
        name: "Google Gemma 4 31B",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "google/gemma-4-26b-a4b-it",
        name: "Google Gemma 4 26B",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "OpenAI GPT-OSS 20B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-nano-9b-v2",
        name: "NVIDIA Nemotron Nano 9B v2",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nemotron-3-ultra",
        name: "NVIDIA Nemotron 3 Ultra",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "inclusionai/ling-3.0-flash",
        name: "Ling-3.0-flash",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "qwen/qwen3.5-coder",
        name: "Qwen 3.5 Coder",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "poolside/laguna-s-2.1-poolside",
        name: "Laguna S 2.1 (Poolside)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "cohere/north-mini-code",
        name: "Cohere North Mini Code",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "poolside/laguna-xs-2.1",
        name: "Laguna XS 2.1",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "poolside/laguna-m.1",
        name: "Laguna M.1",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-nano-30b-a3b",
        name: "NVIDIA Nemotron 3 Nano 30B A3B",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-nano-omni",
        name: "NVIDIA Nemotron Nano Omni",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-nano-9b-v2",
        name: "NVIDIA Nemotron Nano 9B v2",
        contextWindow: 128000,
        maxOutput: 4096,
      },
      {
        id: "nvidia/llama-nemotron-rerank-vl-1b-v2",
        name: "Llama Nemotron Rerank VL 1B V2",
        contextWindow: 10000,
        maxOutput: 2048,
      },
      {
        id: "nvidia/nemotron-nano-12b-2-vl",
        name: "NVIDIA Nemotron Nano 12B 2 VL",
        contextWindow: 128000,
        maxOutput: 4096,
      },
      {
        id: "google/gemma-4-26b-a4b-it",
        name: "Google Gemma 4 26B A4B IT",
        contextWindow: 262000,
        maxOutput: 8192,
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    requiresApiKey: true,
    docsUrl: "https://console.groq.com/keys",
    models: [
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "whisper-large-v3",
        name: "Whisper Large v3",
        contextWindow: 30000,
        maxOutput: 4096,
      },
      {
        id: "whisper-large-v3-turbo",
        name: "Whisper Large v3 Turbo",
        contextWindow: 30000,
        maxOutput: 4096,
      },
      {
        id: "llama-3.2-90b-vision-preview",
        name: "Llama 3.2 90B Vision",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "mixtral-8x7b-32768",
        name: "Mixtral 8x7B",
        contextWindow: 32768,
        maxOutput: 4096,
      },
    ],
  },
];