import { AspectRatio, AIProviderOption } from "./types";

export const ASPECT_RATIOS: Record<string, AspectRatio> = {
  "1:1": { id: "1:1", label: "Square 1:1", ratio: "1:1", width: 1080, height: 1080 },
  "4:5": { id: "4:5", label: "Portrait 4:5", ratio: "4:5", width: 1080, height: 1350 },
  "9:16": { id: "9:16", label: "Story 9:16", ratio: "9:16", width: 1080, height: 1920 },
  "16:9": { id: "16:9", label: "Landscape 16:9", ratio: "16:9", width: 1920, height: 1080 },
  "A4-P": { id: "A4-P", label: "A4 Portrait", ratio: "A4 Portrait", width: 794, height: 1123 },
  "A4-L": { id: "A4-L", label: "A4 Landscape", ratio: "A4 Landscape", width: 1123, height: 794 },
  letter: { id: "letter", label: "Letter", ratio: "Letter", width: 816, height: 1056 },
  custom: { id: "custom", label: "Custom", ratio: "Custom", width: 800, height: 800 },
};

export const AI_PROVIDERS: AIProviderOption[] = [
  {
    id: "openrouter",
    name: "OpenRouter",
    requiresApiKey: true,
    docsUrl: "https://openrouter.ai/keys",
    models: [
      {
        id: "openrouter/free",
        name: "OpenRouter Free (Auto-Select)",
        contextWindow: 8192,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nemotron-3-ultra-550b-a55b:free",
        name: "NVIDIA Nemotron 3 Ultra 550B (Free)",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-super-120b-a12b:free",
        name: "NVIDIA Nemotron 3 Super 120B (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3.5-lightning-30b-a3b:free",
        name: "NVIDIA Nemotron 3.5 Lightning 30B (Free)",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-nano-30b-a3b:free",
        name: "NVIDIA Nemotron 3 Nano 30B (Free)",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-nano-9b-v2:free",
        name: "NVIDIA Nemotron Nano 9B v2 (Free)",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nemotron-nano-12b-2-vl:free",
        name: "NVIDIA Nemotron Nano 12B 2 VL (Free)",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "openai/gpt-oss-120b:free",
        name: "OpenAI GPT-OSS 120B (Free)",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-20b:free",
        name: "OpenAI GPT-OSS 20B (Free)",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "google/gemma-4-31b-it:free",
        name: "Google Gemma 4 31B (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "google/gemma-4-26b-a4b-it:free",
        name: "Google Gemma 4 26B A4B (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "poolside/laguna-s-2.1:free",
        name: "Poolside Laguna S 2.1 (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "poolside/laguna-xs-2.1:free",
        name: "Poolside Laguna XS 2.1 (Free)",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "cohere/north-mini-code:free",
        name: "Cohere North Mini Code (Free)",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "dots-studio/dots3-note-preview:free",
        name: "Dots3 Note Preview (Free)",
        contextWindow: 512000,
        maxOutput: 8192,
      },
    ],
  },
  {
    id: "nim",
    name: "NVIDIA NIM",
    requiresApiKey: true,
    docsUrl: "https://build.nvidia.com/explore/discover",
    models: [
      {
        id: "meta/llama-3.3-70b-instruct",
        name: "Llama 3.3 70B Instruct",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-ultra-550b-a55b",
        name: "Nemotron 3 Ultra 550B",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-super-120b-a12b",
        name: "Nemotron 3 Super 120B",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3.5-lightning-30b-a3b",
        name: "Nemotron 3.5 Lightning 30B",
        contextWindow: 1000000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/nemotron-3-nano-30b-a3b",
        name: "Nemotron 3 Nano 30B",
        contextWindow: 256000,
        maxOutput: 8192,
      },
      {
        id: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
        name: "Nemotron Ultra 253B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "nvidia/llama-3.3-nemotron-super-49b-v1.5",
        name: "Nemotron Super 49B v1.5",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "nvidia/llama-3.1-nemotron-nano-8b-v1",
        name: "Nemotron Nano 8B v1",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nvidia-nemotron-nano-9b-v2",
        name: "Nemotron Nano 9B v2",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "nvidia/nemotron-mini-4b-instruct",
        name: "Nemotron Mini 4B",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "mistralai/mistral-nemotron",
        name: "Mistral Nemotron",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "mistralai/mixtral-8x22b-instruct",
        name: "Mixtral 8x22B Instruct",
        contextWindow: 65536,
        maxOutput: 8192,
      },
      {
        id: "mistralai/mixtral-8x7b-instruct",
        name: "Mixtral 8x7B Instruct",
        contextWindow: 32768,
        maxOutput: 4096,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT-OSS 120B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT-OSS 20B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "qwen/qwen3-next-80b-a3b-instruct",
        name: "Qwen3 Next 80B A3B",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "moonshotai/kimi-k2-instruct",
        name: "Kimi K2 Instruct",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "deepseek-ai/deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "meta/llama-3.1-8b-instruct",
        name: "Llama 3.1 8B Instruct",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "microsoft/phi-4-mini-instruct",
        name: "Phi-4 Mini Instruct",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "deepseek-ai/deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "moonshotai/kimi-k2-thinking",
        name: "Kimi K2 Thinking",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "qwen/qwen3-coder-480b-a35b-instruct",
        name: "Qwen3 Coder 480B",
        contextWindow: 262000,
        maxOutput: 8192,
      },
      {
        id: "z-ai/glm5.1",
        name: "GLM 5.1",
        contextWindow: 131072,
        maxOutput: 8192,
      },
    ],
  },
  {
    id: "groq",
    name: "Groq",
    requiresApiKey: true,
    docsUrl: "https://console.groq.com/keys",
    models: [
      {
        id: "llama-3.1-8b-instant",
        name: "Llama 3.1 8B Instant",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "llama-3.3-70b-versatile",
        name: "Llama 3.3 70B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "meta-llama/llama-4-scout-17b-16e-instruct",
        name: "Llama 4 Scout 17B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-20b",
        name: "GPT OSS 20B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "openai/gpt-oss-120b",
        name: "GPT OSS 120B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "qwen/qwen3-32b",
        name: "Qwen3 32B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "groq/compound",
        name: "Groq Compound",
        contextWindow: 131072,
        maxOutput: 8192,
      },
    ],
  },
  {
    id: "mistral",
    name: "Mistral",
    requiresApiKey: true,
    docsUrl: "https://console.mistral.ai/api-keys/",
    models: [
      {
        id: "mistral-large-latest",
        name: "Mistral Large",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "mistral-small-latest",
        name: "Mistral Small",
        contextWindow: 32768,
        maxOutput: 8192,
      },
      {
        id: "ministral-8b-latest",
        name: "Ministral 8B",
        contextWindow: 131072,
        maxOutput: 8192,
      },
      {
        id: "ministral-3b-latest",
        name: "Ministral 3B",
        contextWindow: 131072,
        maxOutput: 4096,
      },
      {
        id: "open-mixtral-8x22b",
        name: "Mixtral 8x22B",
        contextWindow: 65536,
        maxOutput: 8192,
      },
      {
        id: "open-mixtral-8x7b",
        name: "Mixtral 8x7B",
        contextWindow: 32768,
        maxOutput: 4096,
      },
      {
        id: "open-mistral-7b",
        name: "Mistral 7B",
        contextWindow: 32768,
        maxOutput: 4096,
      },
      {
        id: "codestral-latest",
        name: "Codestral",
        contextWindow: 32768,
        maxOutput: 8192,
      },
    ],
  },
];